name: Feature request
description: Suggest a new feature for this project, which isn't existing yet.
title: "type a short title of your feature request here"
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        - If you're requesting an improvement for an existing feature, then please consider filling out an "enhancement request" instead!
        - If you want to report a bug or an error, then please consider filling out a "bug report" instead!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen and why.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the enhancement request here.
    validations:
      required: false
